baseURL = "/"
languageCode = "en-us"
title = "Xing GUO's Site"
theme = "xmin"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
disqusShortname = "higuoxing"
footnotereturnlinkcontents = "↩"
PygmentsCodeFences = true
PygmentsStyle = "emacs"

[taxonomies]
  tag = "tags"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "$Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 2

[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 3

[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy;  2017 -- 2020 [Xing GUO](https://higuoxing.com/) | Powered by [Hugo](https://github.com/gohugoio/hugo) | Theme: [Xmin](https://github.com/yihui/hugo-xmin)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true