menu:
    $Home: /
    /Blog: /archives/
    /Ideas: /ideas/
    /LINKS: /links/

favicon: /favicon.png

# Comment
disqus: 
# Analytics
# google-analytics:
ga: UA-111257861-1

# Copyright Infomation
startyear: 2017

# mathjax support
mathjax:
  enable: true
  cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
