menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/higuoxing
    Rss: /atom.xml
    About: /about/

favicon: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-111257861-1

# Copyright Infomation
startyear: 2017

# mathjax support
mathjax:
  enable: true
  cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
